### PR TITLE
Done [New API] : User Data #53

### LINKED ISSUE #53: [New API] : User Data API
### Brief Description 🤓

REST API to fetch mock user data from the json files. The data will contain users details such as first name, last name, gender, address, timezone, phone number and an image. 

### How will you develop it?🤩

Node.js and Express.js

### Deployment

None

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by therahulchaurasia**
# 🎯 User Data API #53 

### Closes #53

# 🗒️ Checklist:

- [✔] I have mentioned the issue number in my Pull Request.
- [✔]  I have gone through `rules of when PR will get merged.` 
- [✔] I have commented my code, particularly in hard-to-understand areas
- [✔] I have created a helpful and easy to understand `README.md`
- [✔] I have followed proper file structure.
- [✔] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @therahulchaurasia, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by therahulchaurasia** [comment]
Hey @dishamodi0910, I hope you can view my PR and let me know if you need some changes.

**Comment by dishamodi0910** [comment]
@therahulchaurasia We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by therahulchaurasia** [comment]
Thanks a lot for accepting my PR. Keep growing🚀

**Pull request merged**
