### PR TITLE
Added CryptoApi 

### LINKED ISSUE #30: [Existing API Name] :  CryptoCurrencies Apis provided by wazirx
### Brief Description 🤓

Wazirx is a platform where use can sell and buy cryptocurrencies , It provides an Apis which consist of the prices of popular coins in ruppes . It is giving the data about total trading of the popular coins in 24 hrs.

### Provide reference!

https://cryptocointracker.com/api/wazirx

### Select the open source program you are contributing to

hacktoberfest-23

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by vikrampatel0408**
# 🎯 CryptoCurrencies Apis #30 

### Closes #30 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @vikrampatel0408, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by vikrampatel0408** [comment]
I have updated my Pull Request

**Comment by dishamodi0910** [comment]
@vikrampatel0408 Awesome!🚀

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@vikrampatel0408 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
